/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface MultiSigWalletFactoryInterface extends utils.Interface {
  functions: {
    "createWallet(address[],uint256)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "createWallet"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createWallet",
    values: [PromiseOrValue<string>[], PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "createWallet",
    data: BytesLike
  ): Result;

  events: {
    "WalletInstantiation(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "WalletInstantiation"): EventFragment;
}

export interface WalletInstantiationEventObject {
  sender: string;
  instantiation: string;
}
export type WalletInstantiationEvent = TypedEvent<
  [string, string],
  WalletInstantiationEventObject
>;

export type WalletInstantiationEventFilter =
  TypedEventFilter<WalletInstantiationEvent>;

export interface MultiSigWalletFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MultiSigWalletFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createWallet(
      _owners: PromiseOrValue<string>[],
      _required: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  createWallet(
    _owners: PromiseOrValue<string>[],
    _required: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createWallet(
      _owners: PromiseOrValue<string>[],
      _required: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "WalletInstantiation(address,address)"(
      sender?: null,
      instantiation?: null
    ): WalletInstantiationEventFilter;
    WalletInstantiation(
      sender?: null,
      instantiation?: null
    ): WalletInstantiationEventFilter;
  };

  estimateGas: {
    createWallet(
      _owners: PromiseOrValue<string>[],
      _required: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createWallet(
      _owners: PromiseOrValue<string>[],
      _required: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
